# Generated by Django 6.0.5 on 2026-05-08 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateTimeField(auto_now_add=True)),
                ('fecha_checkout', models.DateTimeField(blank=True, null=True)),
                ('precio_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estancias', to='hotel.habitacion')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estancia', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Estancia',
                'verbose_name_plural': 'Estancias',
            },
        ),
        migrations.CreateModel(
            name='CargoEstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('HABITACION', 'Habitación'), ('RESTAURANTE', 'Restaurante'), ('LAVANDERIA', 'Lavandería'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='estancias.estancia')),
            ],
            options={
                'verbose_name': 'Cargo de Estancia',
                'verbose_name_plural': 'Cargos de Estancia',
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('estancia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='estancias.estancia')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
            },
        ),
    ]
