# Generated by Django 4.2.30 on 2026-07-16 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0004_hotel_cobrar_early_checkin_and_more'),
        ('estancias', '0003_pago_reserva_alter_pago_folio_reembolso'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialHabitacionEstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('diferencia_tarifaria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Habitación',
                'verbose_name_plural': 'Historiales de Cambios de Habitación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='exonerado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='exonerado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_exonerados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='motivo_exoneracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='cargoestancia',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='monto_cargo_positivo'),
        ),
        migrations.AddField(
            model_name='historialhabitacionestancia',
            name='estancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_habitaciones', to='estancias.estancia'),
        ),
        migrations.AddField(
            model_name='historialhabitacionestancia',
            name='habitacion_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones_salida_historial', to='hotel.habitacion'),
        ),
        migrations.AddField(
            model_name='historialhabitacionestancia',
            name='habitacion_nueva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones_entrada_historial', to='hotel.habitacion'),
        ),
        migrations.AddField(
            model_name='historialhabitacionestancia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_habitacion_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
