# Generated by Django 5.2.16 on 2026-07-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0004_historialhabitacionestancia_cargoestancia_exonerado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estancia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario recepcionista que registró el check-in (HOT-HOS-002).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estancias_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
