# Generated by Django 5.2.16 on 2026-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0005_add_registrado_por_estancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoestancia',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
