# Generated by Django 5.2.16 on 2026-07-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0006_cargoestancia_cantidad'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoestancia',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='inventario.producto'),
        ),
    ]
