# Generated by Django 6.0.5 on 2026-05-08 22:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.TextField()),
                ('estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('telefono', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenidades', models.JSONField(default=list)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_habitacion', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('LIMPIEZA', 'En Limpieza'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.hotel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'unique_together': {('hotel', 'numero')},
            },
        ),
    ]
