# Generated by Django 4.2.30 on 2026-07-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_habitacion_imagenes_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cobrar_early_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='early_checkin_monto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='early_checkin_rol_exonerar',
            field=models.CharField(default='administrador', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='early_checkin_tipo_cargo',
            field=models.CharField(choices=[('FIJO', 'Monto Fijo'), ('PORCENTAJE', 'Porcentaje')], default='FIJO', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='early_checkin_tolerancia_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='hotel',
            name='late_checkout_hora_maxima',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='late_checkout_horas_bloque',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='hotel',
            name='late_checkout_monto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.35, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='late_checkout_rol_exonerar',
            field=models.CharField(default='administrador', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='late_checkout_tipo_cargo',
            field=models.CharField(choices=[('FIJO', 'Monto Fijo'), ('PORCENTAJE', 'Porcentaje')], default='PORCENTAJE', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='late_checkout_tolerancia_minutos',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='permitir_early_checkin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='permitir_late_checkout',
            field=models.BooleanField(default=True),
        ),
    ]
