# Generated by Django 5.2.16 on 2026-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_cobrar_early_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='alerta_checkout_minutos',
            field=models.PositiveIntegerField(choices=[(15, '15 minutos antes'), (30, '30 minutos antes'), (60, '60 minutos antes')], default=30, help_text='Minutos antes del checkout para mostrar alerta al recepcionista.'),
        ),
    ]
