# Generated by Django 5.2.16 on 2026-07-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_seed_room_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hora_checkin_estandar',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hora_checkout_estandar',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
