# Generated by Django 5.2.16 on 2026-07-16 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estancias', '0004_historialhabitacionestancia_cargoestancia_exonerado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_atencion', models.CharField(blank=True, max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('INFORMACION', 'Información'), ('LIMPIEZA', 'Limpieza'), ('MANTENIMIENTO', 'Mantenimiento'), ('SERVICIO_HABITACION', 'Servicio a la habitación'), ('RECLAMO', 'Reclamo'), ('EMERGENCIA', 'Emergencia'), ('CONSULTA', 'Consulta'), ('OTRO', 'Otro')], max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=15)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('PROCESO', 'En Proceso'), ('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=15)),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(choices=[('RECEPCION', 'Recepción'), ('HOUSEKEEPING', 'Housekeeping'), ('MANTENIMIENTO', 'Mantenimiento'), ('ADMINISTRACION', 'Administración')], default='RECEPCION', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('solucion', models.TextField(blank=True, null=True)),
                ('observacion_resolucion', models.TextField(blank=True, null=True)),
                ('motivo_reapertura', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='estancias.estancia')),
                ('recepcionista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Servicio',
                'verbose_name_plural': 'Tickets de Servicio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('estado_ticket', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='atencion.ticketservicio')),
            ],
            options={
                'verbose_name': 'Seguimiento de Ticket',
                'verbose_name_plural': 'Seguimientos de Tickets',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
