# Generated by Django 5.2.16 on 2026-07-16 19:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estancias', '0007_cargoestancia_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_egresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_esperado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('observacion_apertura', models.TextField(blank=True, null=True)),
                ('observacion_cierre', models.TextField(blank=True, null=True)),
                ('arqueada', models.BooleanField(default=False)),
                ('fecha_arqueo', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='AnomaliaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('FALTANTE', 'Faltante de Efectivo'), ('SOBRANTE', 'Sobrante de Efectivo'), ('BILLETE_FALSO', 'Billete Falso'), ('COMPROBANTE_DUPLICADO', 'Comprobante Duplicado'), ('PAGO_RECHAZADO', 'Pago Rechazado'), ('OTRO', 'Otro')], default='OTRO', max_length=25)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('observacion', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_caja_resueltas', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='caja.caja')),
            ],
            options={
                'verbose_name': 'Anomalía de Caja',
                'verbose_name_plural': 'Anomalías de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('concepto', models.CharField(choices=[('PAGO_RESERVA', 'Pago Reserva (Anticipo)'), ('PAGO_HOSPEDAJE', 'Pago Hospedaje'), ('PAGO_CONSUMOS', 'Pago Consumos'), ('REEMBOLSO', 'Reembolso'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], default='EFECTIVO', max_length=20)),
                ('descripcion', models.TextField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.caja')),
                ('pago_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='estancias.pago')),
                ('reembolso_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='estancias.reembolso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
