# Generated by Django 6.0.5 on 2026-05-08 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('num_adultos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CHECKIN', 'Check-In realizado'), ('CHECKOUT', 'Check-Out realizado'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('origen', models.CharField(choices=[('DIRECTO', 'Directo'), ('WEB', 'Web'), ('AGENCIA', 'Agencia')], default='DIRECTO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='hotel.habitacion')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.hotel')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='huespedes.huesped')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='hotel.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
