# Generated by Django 6.0.5 on 2026-07-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_horarios_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
