# Generated by Django 5.2.16 on 2026-07-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_motivo_cancelacion_reserva_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CHECKIN', 'Check-In realizado'), ('CHECKOUT', 'Check-Out realizado'), ('CANCELADA', 'Cancelada'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20),
        ),
    ]
